[package]
name = "particles"
version = "0.1.0"
authors = ["beam-mw <alex@beam-mw.com>"]
edition = "2018"

[dependencies]
uuid = "0.7"
rand = "0.6"
piston = "0.42.0"
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.54.0"
piston2d-opengl_graphics = "0.59.0"